name: lesscompile
description: Lessompile is a transformer of .less -> .css for Dart projects
author: Mikhail Turilin <mikhail@turilin.com>
homepage: https://github.com/mturilin/lesscompile
version: 0.0.5
dependencies:
    barback: ">=0.14.0+3 <0.15.0"
    ini: ">=1.0.1 <2.0.0"
dev_dependencies:
transformers: