name: lesscompile
description: Lessompile is a transformer of .less -> .css for Dart projects
author: Mikhail Turilin <mikhail@turilin.com>
homepage: https://github.com/mturilin/lesscompile
version: 0.0.4
dependencies:
    barback: any
    ini: any
dev_dependencies:
transformers: