name: lesscompile
description: Lessompile is a transformer of .less -> .css for Dart projects
author: Mikhail Turilin <mikhail@turilin.com>
homepage: https://github.com/mturilin/lesscompile
version: 0.0.5
dependencies:
    barback: any
    ini: ">=1.0.1"
dev_dependencies:
transformers: